using Content.Shared._ROBUST.Match;
using Robust.Client.AutoGenerated;
using Robust.Client.UserInterface;
using Robust.Client.UserInterface.XAML;

namespace Content.Client._ROBUST.Match.MatchSelectionBUI.SettingWidgets;

[GenerateTypedNameReferences]
public sealed partial class DropdownSelectorSetting : Control, ISettingsWidget
{
    private readonly string _settingName;

    // todo: these shouldn't all be strings but its ok for now
    public DropdownSelectorSetting(string name, Dictionary<string, string> settings)
    {
        RobustXamlLoader.Load(this);
        IoCManager.InjectDependencies(this);

        _settingName = name;

        foreach (var setting in settings)
        {
            var id = Dropdown.ItemCount;

            Dropdown.AddItem(setting.Key, id);
            Dropdown.SetItemMetadata(id, setting.Value);
        }

        Dropdown.OnItemSelected += args =>
        {
            Dropdown.SelectId(args.Id);
        };
    }

    public void GetSetting(ref MatchSettings matchSettings)
    {
        matchSettings.Settings.Add(_settingName, (string) Dropdown.SelectedMetadata!);
    }
}
