using Content.Client.UserInterface.Controls;
using Content.Shared._ROBUST.CCVar;
using Robust.Client;
using Robust.Client.AutoGenerated;
using Robust.Client.UserInterface.XAML;
using Robust.Shared.Configuration;
using Robust.Shared.Network;

namespace Content.Client._ROBUST.ServerSelection;

[GenerateTypedNameReferences]
public sealed partial class ServerSelectionWindow : FancyWindow
{
    [Dependency] private IClientNetManager _net = default!;
    [Dependency] private IConfigurationManager _cfg = default!;
    [Dependency] private IGameController _gameController = default!;

    public ServerSelectionWindow()
    {
        RobustXamlLoader.Load(this);
        IoCManager.InjectDependencies(this);

        // set up server list
        var serversUnparsed = _cfg.GetCVar(RobustCCVars.MutliServerOtherServers);

        var servers = serversUnparsed.Split(',');

        foreach (var server in servers)
        {
            var id = ServerDropdown.ItemCount;

            var name = server.Split("|")[0];

            ServerDropdown.AddItem(name, id);
            ServerDropdown.SetItemMetadata(id, server);
        }

        ServerDropdown.OnItemSelected += args =>
        {
            ServerDropdown.SelectId(args.Id);
        };

        // setup ping

        var ping = _net.ServerChannel!.Ping;

        PingLabel.Text = ping.ToString();
        PingLabel.FontColorOverride = ping switch
        {
            < 75 => Color.Green,
            < 200 => Color.Yellow,
            _ => Color.Red,
        };

        // setup button
        SelectServerButton.OnPressed += _ =>
        {
            var server = (string)ServerDropdown.SelectedMetadata!;

            var name = server.Split('|')[0];
            var ip = server.Split('|')[1];
            var port = server.Split('|')[2];

            _gameController.Redial($"ss14://{ip}:{port}", $"Joining server {name}!");
        };

    }


}
