using System.Numerics;
using Content.Client.Resources;
using Content.Client.UserInterface.Controls;
using Content.Shared.EntityEffects.Effects.EntitySpawning;
using Robust.Client.AutoGenerated;
using Robust.Client.GameObjects;
using Robust.Client.Graphics;
using Robust.Client.ResourceManagement;
using Robust.Client.UserInterface;
using Robust.Client.UserInterface.Controls;
using Robust.Client.UserInterface.XAML;
using Robust.Shared.Prototypes;

namespace Content.Client._ROBUST.Match.Kits;

[GenerateTypedNameReferences]
public sealed partial class KitSelectionWindow : FancyWindow
{
    [Dependency] private IPrototypeManager _proto = default!;
    [Dependency] private IEntityManager _ent = default!;
    [Dependency] private IResourceCache _cache = default!;

    private readonly SpriteSystem _sprite;

    private List<Dictionary<string, List<EntProtoId>>> Kits;

    public event Action<int>? OnKitChosen;

    public KitSelectionWindow(List<Dictionary<string, List<EntProtoId>>> kits)
    {
        RobustXamlLoader.Load(this);
        IoCManager.InjectDependencies(this);

        _sprite = _ent.System<SpriteSystem>();

        // Save the proto so we can use it later.
        Kits = kits;

        for (var i=0; i < Kits.Count; i++)
        {
            var kit = Kits[i];
            CreateKit(kit, i);
        }

        // PopulateWindow();
    }

    // TODO change this to an object w/ setter
    private void CreateKit(Dictionary<string, List<EntProtoId>> kit, int kitNumber)
    {
        var container = new BoxContainer
        {
            Orientation = BoxContainer.LayoutOrientation.Vertical,
            Margin = new Thickness(10,10,10,10),
            HorizontalAlignment = HAlignment.Center,
        };
        // <PanelContainer HorizontalExpand="True" StyleClasses="PanelDark">

        var panelContainer = new PanelContainer()
        {
            HorizontalExpand = true,
            VerticalExpand = true,
            StyleClasses = { "PanelLight" },
        };

        var secondContainer = new BoxContainer()
        {
            Orientation = BoxContainer.LayoutOrientation.Vertical,
            Margin = new Thickness(10, 10, 10, 10),
            HorizontalAlignment = HAlignment.Center,
        };

        panelContainer.AddChild(secondContainer);

        var title = new Label
        {
            Text = $"Kit {kitNumber}: ",
            Margin = new Thickness(0,0,0,5),
            HorizontalAlignment = HAlignment.Center,
            FontOverride = _cache.GetFont("/Fonts/NotoSansDisplay/NotoSansDisplay-Regular.ttf", 17),
        };

        container.AddChild(title);

        container.AddChild(panelContainer);


        foreach (var entry in kit)
        {
            // List<Texture> textures = new();

            var label = new RichTextLabel
            {
                Text = $"[bold]{entry.Key}[/bold]",
                Margin = new Thickness(5,0,0,0),
                HorizontalAlignment = HAlignment.Center,
            };
            secondContainer.AddChild(label);

            var imagesContainer = new BoxContainer()
            {
                Orientation = BoxContainer.LayoutOrientation.Horizontal,
                HorizontalAlignment = HAlignment.Center,
            };

            secondContainer.AddChild(imagesContainer);

            var prototypes = new Dictionary<EntityPrototype, int>();

            foreach (var protoId in entry.Value)
            {
                // var ent = _ent.Spawn(protoId);
                // var metadata = _ent.GetComponent<MetaDataComponent>(ent);
                var entPrototype = _proto.Index<EntityPrototype>(protoId);

                if (!prototypes.TryAdd(entPrototype, 1))
                    prototypes[entPrototype] += 1;

                // imageContainer.AddChild(image);
                // textures.Add(sprite);
                // _ent.DeleteEntity(ent);
            }

            foreach (var prototypeToNum in prototypes)
            {
                var prototype = prototypeToNum.Key;
                var texture = _sprite.Frame0(prototype);

                var image = new TextureRect
                {
                    Texture = texture,
                    TextureScale = new Vector2(2, 2),
                    ToolTip = prototype.Name, // todo: this doesn't seem to work
                };

                var amountLabel = new Label
                {
                    Text = $"{prototypeToNum.Value}x",
                    FontOverride = _cache.GetFont("/Fonts/NotoSansDisplay/NotoSansDisplay-Regular.ttf", 11),
                    // Margin = new Thickness(0, 0, 2, 5),
                    VerticalAlignment = VAlignment.Bottom,
                };

                var textureContainer = new Control
                {
                    Margin = new Thickness(5, 0, 5, 0),
                };

                textureContainer.AddChild(image);
                textureContainer.AddChild(amountLabel);

                imagesContainer.AddChild(textureContainer);
            }


            // container.AddChild(label);
        }


        var button = new Button
        {
            Text = "Select Kit!",
            Margin = new Thickness(0,10,0,10),
        };

        button.OnPressed += _ => OnKitChosen?.Invoke(kitNumber);

        container.AddChild(button);

        MainContainer.AddChild(container);
    }
}
