using System.Linq;
using System.Numerics;
using Content.Client._ROBUST.Match.MatchSelectionBUI.SettingWidgets;
using Content.Client.Resources;
using Content.Client.UserInterface.Controls;
using Content.Shared._ROBUST.Match;
using Robust.Client.AutoGenerated;
using Robust.Client.GameObjects;
using Robust.Client.ResourceManagement;
using Robust.Client.UserInterface;
using Robust.Client.UserInterface.Controls;
using Robust.Client.UserInterface.XAML;
using Robust.Shared.Prototypes;

namespace Content.Client._ROBUST.Match.MatchSelectionBUI;

[GenerateTypedNameReferences]
public sealed partial class MatchSelectionWindow : FancyWindow
{
    [Dependency] private IPrototypeManager _proto = default!;
    [Dependency] private IEntityManager _ent = default!;
    [Dependency] private IResourceCache _cache = default!;

    public event Action<(ProtoId<MatchPrototype>, MatchSettings)>? OnMatchStarted;

    private EntityUid? CurrentlySelectedMatch;

    public MatchSelectionWindow()
    {
        RobustXamlLoader.Load(this);
        IoCManager.InjectDependencies(this);

        MatchTypes.OnItemSelected += args =>
        {
            MatchTypes.SelectId(args.Id);
            RefreshSettings();
        };

        StartMatchButton.OnPressed += GetSelectedMatch;
    }

    private void GetSelectedMatch(BaseButton.ButtonEventArgs obj)
    {
        var selectedProto = MatchTypes.SelectedMetadata;

        if (selectedProto is not string protoString)
            return;

        var protoId = new  ProtoId<MatchPrototype>(protoString);

        // get settings!

        var settings = new MatchSettings();

        foreach (var child in SettingsContainer.Children)
        {
            if (child is not ISettingsWidget settingsWidget)
                throw new Exception("Setting is not settings widget!");

            settingsWidget.GetSetting(ref settings);
        }

        OnMatchStarted?.Invoke((protoId, settings));

        Close();
    }

    public void AddMatches()
    {
        var matchTypes = _proto.EnumeratePrototypes<MatchPrototype>().OrderBy(m => m.ID).ToList();

        foreach (var match in matchTypes)
        {
            var id = MatchTypes.ItemCount;

            MatchTypes.AddItem(match.MatchName, id);
            MatchTypes.SetItemMetadata(id, match.ID);
        }

        // todo: this doesn't trigger the selection event, that should probably be updated in RT?
        MatchTypes.SelectId(0);

        RefreshSettings();
    }

    private void RefreshSettings()
    {
        var selectedId = MatchTypes.SelectedId;

        _ent.DeleteEntity(CurrentlySelectedMatch);

        SettingsContainer.RemoveAllChildren();

        var matchProto = _proto.Index<MatchPrototype>((string) MatchTypes.GetItemMetadata(selectedId)!);

        CurrentlySelectedMatch = _ent.Spawn(matchProto.MatchEntProtoId);

        var settingsEvent = new GetSettingsFromMatchEvent();

        _ent.EventBus.RaiseLocalEvent(CurrentlySelectedMatch.Value, ref settingsEvent);

        foreach (var setting in settingsEvent.Settings)
        {
            SettingsContainer.AddChild(setting);
        }
    }
}

[ByRefEvent]
public sealed class GetSettingsFromMatchEvent
{
    public List<Control> Settings = new();
};
