using Content.Client._ROBUST.Match.Timer;
using Content.Client.UserInterface.Controls;
using Robust.Client.AutoGenerated;
using Robust.Client.ResourceManagement;
using Robust.Client.UserInterface.XAML;
using Robust.Shared.Prototypes;

namespace Content.Client._ROBUST.Match.MatchConfirm;

[GenerateTypedNameReferences]
public sealed partial class MatchConfirmWindow : FancyWindow
{
    [Dependency] private IPrototypeManager _proto = default!;
    [Dependency] private IEntityManager _ent = default!;
    [Dependency] private IResourceCache _cache = default!;

    public event Action? OnConfirm;

    public MatchConfirmWindow(string username)
    {
        RobustXamlLoader.Load(this);
        IoCManager.InjectDependencies(this);

        OtherUsername.Text = username;

        CountdownTimer.TimeFormat = TimeFormat.SecondsMilliseconds;
        CountdownTimer.StartCountdown(TimeSpan.FromSeconds(10));
        CountdownTimer.OnTimerFinished += Close;

        ConfirmButton.OnPressed += _ =>  OnConfirm?.Invoke();
    }
}
