using Content.Client.Resources;
using Robust.Client.AutoGenerated;
using Robust.Client.ResourceManagement;
using Robust.Client.UserInterface;
using Robust.Client.UserInterface.Controls;
using Robust.Client.UserInterface.XAML;

namespace Content.Client._ROBUST.Match.Score;

[GenerateTypedNameReferences]
public sealed partial class ScoreBarUI : Control
{
    [Dependency] private IResourceCache _cache = default!;

    public ScoreBarUI()
    {
        RobustXamlLoader.Load(this);
        IoCManager.InjectDependencies(this);
    }

    // todo remove this evil method, do it in the constructor

    public void SetFonts()
    {
        YourScore.FontOverride = _cache.GetFont("/Fonts/NotoSansDisplay/NotoSansDisplay-Bold.ttf", 24);
        OpponentsScore.FontOverride = _cache.GetFont("/Fonts/NotoSansDisplay/NotoSansDisplay-Bold.ttf", 24);
        Middle.FontOverride = _cache.GetFont("/Fonts/NotoSansDisplay/NotoSansDisplay-Regular.ttf", 20);

        Footer.FontOverride = _cache.GetFont("/Fonts/NotoSansDisplay/NotoSansDisplay-Regular.ttf", 10);

        // Footer.FontOverride = cache.GetFont("/Fonts/NotoSansDisplay/NotoSansDisplay-Bold.ttf", 10);
    }

    // public ScoreBarUI(IResourceCache resourceCache)
    // {
    //     YourScore.FontOverride = resourceCache.GetFont("/Fonts/NotoSansDisplay/NotoSansDisplay-Bold.ttf", 24);
    //     OpponentsScore.FontOverride = resourceCache.GetFont("/Fonts/NotoSansDisplay/NotoSansDisplay-Bold.ttf", 24);
    //
    //     Footer.FontOverride = resourceCache.GetFont("/Fonts/NotoSansDisplay/NotoSansDisplay-Bold.ttf", 10);
    //
    //     RobustXamlLoader.Load(this);
    // }
}
