using Robust.Client.AutoGenerated;
using Robust.Client.UserInterface;
using Robust.Client.UserInterface.Controls;
using Robust.Client.UserInterface.XAML;
using Robust.Shared.Timing;

namespace Content.Client._ROBUST.Match.Timer;

[GenerateTypedNameReferences]
public sealed partial class CountdownTimer : Control
{
    [Dependency] private IGameTiming _timing = default!;

    private TimeSpan? _startTime;

    private TimeSpan? _timerLength;

    public TimeFormat TimeFormat = TimeFormat.SecondsMilliseconds;

    public Action? OnTimerFinished;

    public CountdownTimer()
    {
        RobustXamlLoader.Load(this);
        IoCManager.InjectDependencies(this);
    }

    public void StartCountdown(TimeSpan timerLength)
    {
        _timerLength = timerLength;
        _startTime = _timing.CurTime;
    }

    private void SetTime(TimeSpan time)
    {
        // todo: make seconds be larger and not cap out at 60
        CountDown.Text = TimeFormat switch
        {
            TimeFormat.MinutesSecondsMilliseconds => time.ToString(@"mm\:ss\.ff"),
            TimeFormat.SecondsMilliseconds        => time.ToString(@"ss\.ff"),
            TimeFormat.Seconds                    => time.ToString("ss"),
            _                                     => time.ToString(),
        };
    }

    protected override void FrameUpdate(FrameEventArgs args)
    {
        base.FrameUpdate(args);

        if (_startTime == null || _timerLength == null)
            return;

        if (_timing.CurTime >= _startTime + _timerLength)
        {
            _startTime = null;
            _timerLength = null;

            SetTime(TimeSpan.FromSeconds(0));

            OnTimerFinished?.Invoke();

            return;
        }

        SetTime(_startTime.Value + _timerLength.Value - _timing.CurTime);
    }
}

public enum TimeFormat
{
    MinutesSecondsMilliseconds,
    SecondsMilliseconds,
    Seconds,
}
